name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t mindplex_landing:$(date +%s)

      - name: run image
        run: docker run -p 3002:8080 mindplex_landing:$(date +%s)
