name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t mindplex_landing

      # - name: run image
      #   run: docker run -p 3002:8080 mindplex_landing
# todo(dave-labs12): automatic deployment to ec2 instance
# EC2-Deploy:
#   runs-on: ubuntu-latest
#   steps:
#     - id: deploy
#       uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
#       with:
#         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws_default_region: us-east-1
#         dot_env: ${{ secrets.DOT_ENV }}
